---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api
  namespace: keptn
spec:
  hosts:
  - "api.keptn.DOMAIN_PLACEHOLDER"
  - "api.keptn"
  gateways:
    - public-gateway.istio-system
  http:
  - match:
    - uri:
        regex: "/v1/project/\\w+/resource"
    - uri:
        regex: "/v1/project/\\w+/stage/\\w+/resource"
    - uri:
        regex: "/v1/project/\\w+/stage/\\w+/service/\\w+/resource"
    route:
    - destination:
        host: configuration-service.keptn.svc.cluster.local
  - route:
    - destination:
        host: api.keptn.svc.cluster.local
        websocketUpgrade: true
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: api
  namespace: keptn
spec:
  host: api.keptn.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: configuration-service
  namespace: keptn
spec:
  host: configuration-service.keptn.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: swagger-ui
  namespace: keptn
spec:
  host: swagger-ui.keptn.svc.cluster.local