apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: keptncontrib/jmeter-extended-service
      docker:    # 	beta describes an artifact built from a Dockerfile.
        dockerfile: Dockerfile
        buildArgs:
          debugBuild: true
deploy:
  kubectl:
    manifests:
      - deploy/service.yaml
